# -*- coding: utf-8 -*-
"""AgentManager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KikSXXpzP1mZ41K8G-QJjKPrzXCSpudZ
"""

from .summarizer_agent import SummarizeTool
from .write_agent import WriteArticleTool
from .sanitizer_agent import SanitizeDataTool
from .summary_validator import SummarizeValidatorAgent
from .writer_validator import WriteArticleValidatorAgent
from .sanitize_validator import SanitizeDataValidatorAgent
from .refiner_agent import RefinerAgent # New import
from .validator_agent import ValidatorAgent  # New import

class AgentManager:
    def __init__(self, max_retries=2, verbose=True):
        self.agents = {
            "summarize": SummarizeTool(max_retries=max_retries, verbose=verbose),
            "write_article": WriteArticleTool(max_retries=max_retries, verbose=verbose),
            "sanitize_data": SanitizeDataTool(max_retries=max_retries, verbose=verbose),
            "summarize_validator": SummarizeValidatorAgent(max_retries=max_retries, verbose=verbose),
            "write_article_validator": WriteArticleValidatorAgent(max_retries=max_retries, verbose=verbose),
            "sanitize_data_validator": SanitizeDataValidatorAgent(max_retries=max_retries, verbose=verbose),
            "refiner": RefinerAgent(max_retries=max_retries, verbose=verbose),      # New agent
            "validator": ValidatorAgent(max_retries=max_retries, verbose=verbose)   # New agent
        }

    def get_agent(self, agent_name):
        agent = self.agents.get(agent_name)
        if not agent:
            raise ValueError(f"Agent '{agent_name}' not found.")
        return agent
