# -*- coding: utf-8 -*-
"""Sanitizer_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZKG3w2TWOZ314xm5I1KBM-hVAj8rS9k
"""

pip install loguru
pip3 install python-dotenv
from agent_base import AgentBase

class SanitizeDataTool(AgentBase):
  def __init__(self,max_entries=3,verbose=True):
    super().__init__(name="SanitizeDataTool",max_retries=max_retries,verbose=verbose)

  def execute(self,medical_data):
    messages = [
        {"role": "system","content": "You are an AI assistant that sanitizes medical data by removing Protected Health Information (PHI)."},
        {
            "role": "user",
            "content":(
                "Remove all PHI from the following data :\n\n"
                f"{medical_data}\n\nSanitized Data :"
            )
        }

    ]
    sanitized_data=self.call_openai(messages,max_tokens=500)
    return sanitized_data
