# -*- coding: utf-8 -*-
"""Summary_Validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trjL02M-fM8RamzKphGQYl0XuWdT-9jA
"""

from .agent_base import AgentBase

class SummarizeValidatorAgent(AgentBase):
    def __init__(self, max_retries=2, verbose=True):
        super().__init__(name="SummarizeValidatorAgent", max_retries=max_retries, verbose=verbose)

        def execute(self,original_text,summary):
          system_message = "You are an AI assistant that validates summaries of medical texts."
          user_content = (
              "Given the original text and its summary, assess whether the summary accurately and concisely captures the key points of the original text.\n"
              "Provide a brief analysis and rate the summary on a scale of 1 to 5, where 5 represents a perfect match.\n\n "
              f"Original Text: {original_text}\n\n"
              f"Summary:\n {summary}\n\n"
              "Validation:"
          )
          messages = [
              {"role": "system", content: system_message},
              {"role": "user", content: user_content}
          ]
          validation=self.call_openai(messages,max_tokens=512)
          return validation
