# -*- coding: utf-8 -*-
"""Write_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Plp0mnTyOo1vAc5oEE0t6Z6tU8m7X-2H
"""

pip install loguru
pip3 install python-dotenv
from agent_base import AgentBase

class WriteArticleTool(AgentBase):
  def __init__(self,max_retries=3,verbose=True):
    super().__init__(name="WriteArticleTool", max_retries=max_retries, verbose=verbose)

    def execute(self,topic,outline=None):
      system_message = "you are an expert academic writer."
      user_content = f"Write a research article on the following topic:\nTopic: {topic}\n\n"
      messages=[
          {"role":"system","content":system_message},
          {"role":"user","content":user_content}
      ]
      article = self.call_openai(messages,max_tokens=1000)
